import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ig' | 'yo' | 'ha' | 'fr' | 'zh';

const translations = {
  en: {
    market: 'Market',
    tracker: 'Tracker',
    sellers: 'Sellers',
    diyHub: 'DIY Hub',
    inbox: 'Inbox',
    garage: 'Garage',
    shop: 'Shop',
    track: 'Track',
    diy: 'DIY',
    sellAPart: 'Sell a Part',
    signIn: 'Sign In',
    nigeriaNumberOne: "Nigeria's #1",
    autoPartsMarketplace: "Auto Parts Marketplace",
    escrowProtected: "Escrow Protected",
    listingsCount: "50k+ Listings",
    liveTracking: "Live Order Tracking",
    searchPlaceholder: "Search for parts (e.g. Brake Pads, Alternator)...",
    filters: "Filters",
    allParts: "All Parts",
    engine: "Engine",
    transmission: "Transmission",
    brakes: "Brakes",
    suspension: "Suspension",
    exterior: "Exterior",
    interior: "Interior",
    viewDetails: "View Details",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    conditionNew: "New",
    conditionUsed: "Used",
    compare: "Compare",
    checkout: "Checkout",
    payNow: "Pay Now",
    orderSuccess: "Order successfully placed!",
    viewReceipt: "View Receipt",
    myGarage: "My Garage",
    manageVehicles: "Manage your vehicles and find exactly what fits.",
    addVehicle: "Add Vehicle",
    primary: "Primary",
    primaryVehicle: "Primary Vehicle",
    noVehicles: "No vehicles in your garage yet.",
    uploadMedia: "Upload Media",
    messages: "Messages",
    noMessages: "No messages selected",
    typeMessage: "Type a message...",
    send: "Send",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    partsSelected: "Parts Selected",
    compareDetails: "Compare Details",
    clear: "Clear",
    noPartsFound: "No parts found matching your criteria",
    reviews: "reviews",
    footer: "© 2025 PartsHub Marketplace. Confidential Roadmap Phase 1 Shipped.",
    wishlist: "Wishlist",
    mechanics: "Mechanics",
    orders: "Orders",
    findMechanic: "Find a Mechanic",
    myOrders: "My Orders",
    savedItems: "Saved Items",
    compareParts: "Compare Parts",
    conditionLabel: "Condition",
    gradeQuality: "Grade / Quality",
    ratingLabel: "Rating",
    descriptionLabel: "Description",
    notSpecified: "Not specified",
    qrScanner: "QR Code Scanner"
  },
  ig: {
    market: 'Ahịa',
    tracker: 'Nsochi',
    sellers: 'Ndị Na-ere',
    diyHub: 'Ebe Mmezi',
    inbox: 'Ozi',
    garage: 'Ebe Idobe Ụgbọala',
    shop: 'Ahịa',
    track: 'Chọta',
    diy: 'Mmezi',
    sellAPart: 'Ree Ngwa',
    signIn: 'Banye',
    nigeriaNumberOne: "Nke mbu na Naịjirịa",
    autoPartsMarketplace: "Ahịa Ngwa Ụgbọala",
    escrowProtected: "Nchekwa Escrow",
    listingsCount: "Ihe karịrị puku iri ise (50k+)",
    liveTracking: "Nsochi nnyefe ozugbo",
    searchPlaceholder: "Chọọ ngwa (dịka Brake, Alternator)...",
    filters: "Nyocha",
    allParts: "Ngwa niile",
    engine: "Igwe",
    transmission: "Nnyefe",
    brakes: "Breek",
    suspension: "Nkwusị",
    exterior: "N'èzí",
    interior: "N'ime",
    viewDetails: "Hụ nkọwa",
    addToCart: "Tinye na nkata",
    buyNow: "Zụrụ ugbu a",
    conditionNew: "Ọhụrụ",
    conditionUsed: "Nke ejiri mee",
    compare: "Jiri tụnyere",
    checkout: "Kwụọ ụgwọ",
    payNow: "Kwụọ ugbu a",
    orderSuccess: "I tinyela iwu nke ọma!",
    viewReceipt: "Hụ akwụkwọ nnata",
    myGarage: "Ebe idobe ụgbọala m",
    manageVehicles: "Jikwaa ụgbọala gị ma chọta ihe ga-adaba.",
    addVehicle: "Tinye ụgbọala",
    primary: "Nke isi",
    primaryVehicle: "Isi ụgbọala",
    noVehicles: "Onwebeghị ụgbọala n'ebe idobe gị.",
    uploadMedia: "Kpesa Midia",
    messages: "Ozi",
    noMessages: "Onweghị ozi ahọpụtara",
    typeMessage: "Pịnye ozi...",
    send: "Ziga",
    cancel: "Kagbuo",
    save: "Chekwaa",
    delete: "Hichapụ",
    partsSelected: "Ngwa ahọpụtara",
    compareDetails: "Tụnyere nkọwa",
    clear: "Fichaa",
    noPartsFound: "Ọ nweghị ngwa dabara",
    reviews: "nyocha",
    footer: "© 2025 Ahịa PartsHub. Edobere ikike niile.",
    wishlist: "Ihe Ndị Na-amasị M",
    mechanics: "Ndị Na-arụ Ụgbọala",
    orders: "Iwu M",
    findMechanic: "Chọta onye na-arụ ụgbọala",
    myOrders: "Iwu m niile",
    savedItems: "Ngwa Edobere",
    compareParts: "Tụnyere Ngwa",
    conditionLabel: "Ọnọdụ",
    gradeQuality: "Ọkwa / Ogo",
    ratingLabel: "Nyocha Ogo",
    descriptionLabel: "Nkọwa",
    notSpecified: "A kọwaghị ya",
    qrScanner: "Nyocha QR Code"
  },
  yo: {
    market: 'Ọjà',
    tracker: 'Ìtọpinpin',
    sellers: 'Àwọn Olùtà',
    diyHub: 'Ibi Àtúnṣe',
    inbox: 'Àpótí Ìwé',
    garage: 'Garájì',
    shop: 'Ṣọ́ọ̀bù',
    track: 'Tọpinpin',
    diy: 'Àtúnṣe',
    sellAPart: 'Ta Ọjà',
    signIn: 'Wọlé',
    nigeriaNumberOne: "Akọkọ ni Naijiria",
    autoPartsMarketplace: "Ọjà Awọn Ẹya Ọkọ",
    escrowProtected: "Aabo Escrow",
    listingsCount: "Ju 50k+ lọ",
    liveTracking: "Itọpinpin laaye",
    searchPlaceholder: "Wa awọn ẹya (b.a. Brake, Alternator)...",
    filters: "Asẹ",
    allParts: "Gbogbo Ẹya",
    engine: "Ẹrọ",
    transmission: "Gbigbe",
    brakes: "Bireki",
    suspension: "Idaduro",
    exterior: "Ita",
    interior: "Inu",
    viewDetails: "Wo alaye rẹ",
    addToCart: "Fi sinu kẹkẹ",
    buyNow: "Ra lowo",
    conditionNew: "Tuntun",
    conditionUsed: "Ti a ti lo",
    compare: "Fi wé",
    checkout: "Sanwo",
    payNow: "Sanwo bayii",
    orderSuccess: "Aṣeyọri aṣẹ idari!",
    viewReceipt: "Wo Iwe Ẹri",
    myGarage: "Garájì mi",
    manageVehicles: "Ṣakoso awọn ọkọ ayọkẹlẹ rẹ ki o wa ohun ti o baamu.",
    addVehicle: "Fi ọkọ ayọkẹlẹ kun",
    primary: "Akọkọ",
    primaryVehicle: "Ọkọ ayọkẹlẹ akọkọ",
    noVehicles: "Ko si ọkọ ayọkẹlẹ ninu garaji rẹ sibẹsibẹ.",
    uploadMedia: "Fi aworan ranṣẹ",
    messages: "Awọn ozi",
    noMessages: "Ko si ozi ti a yan",
    typeMessage: "Tẹ ifiranṣẹ...",
    send: "Firanṣẹ",
    cancel: "Fagilee",
    save: "Fipamọ",
    delete: "Paarẹ",
    partsSelected: "Awọn ẹya ti a yan",
    compareDetails: "Ṣe afiwe awọn alaye",
    clear: "Nu kuro",
    noPartsFound: "Ko si awọn ẹya ti o baamu",
    reviews: "àwọn atunyẹwo",
    footer: "© 2025 Ọjà PartsHub. Gbogbo ẹtọ wa ni ipamọ.",
    wishlist: "Ohun ti a fẹ",
    mechanics: "Awon Mekaniki",
    orders: "Paṣẹ",
    findMechanic: "Wa eeyan ti o n ṣiṣẹ ọkọ",
    myOrders: "Awọn aṣẹ mi",
    savedItems: "Awọn nkan ti a fipamọ",
    compareParts: "Ṣe afiwe Awọn apakan",
    conditionLabel: "Ipo",
    gradeQuality: "Ipele / Didara",
    ratingLabel: "Oṣuwọn",
    descriptionLabel: "Apejuwe",
    notSpecified: "Ko pato",
    qrScanner: "Aworan koodu QR"
  },
  ha: {
    market: 'Kasuwa',
    tracker: 'Bin Diddigi',
    sellers: 'Masu Sayarwa',
    diyHub: 'Cibiyar Gyara',
    inbox: 'Akwatin Saƙo',
    garage: 'Gareji',
    shop: 'Shago',
    track: 'Binciko',
    diy: 'Gyara',
    sellAPart: 'Sayar da Kaya',
    signIn: 'Shiga',
    nigeriaNumberOne: "Na ɗaya a Najeriya",
    autoPartsMarketplace: "Kasuwar Kayan Mota",
    escrowProtected: "Kariyar Escrow",
    listingsCount: "Sama da 50k",
    liveTracking: "Binciken Sakonni kai tsaye",
    searchPlaceholder: "Nemi kayayyaki (misali. Birki, Alternator)...",
    filters: "Tace",
    allParts: "Duk Kayayyaki",
    engine: "Injin",
    transmission: "Giya",
    brakes: "Burki",
    suspension: "Dakatarwa",
    exterior: "Waje",
    interior: "Ciki",
    viewDetails: "Duba cikakkun bayanai",
    addToCart: "Sanya a kwando",
    buyNow: "Saya Yanzu",
    conditionNew: "Sabbi",
    conditionUsed: "Gwanjo",
    compare: "Kwatanta",
    checkout: "Biya",
    payNow: "Biya Yanzu",
    orderSuccess: "An yi nasarar yin oda!",
    viewReceipt: "Duba Rasidi",
    myGarage: "Gareji na",
    manageVehicles: "Sarrafa motocin ku kuma nemo ainihin abin da ya dace.",
    addVehicle: "Ƙara Mota",
    primary: "Babban",
    primaryVehicle: "Babban Mota",
    noVehicles: "Babu motoci a garejin ku tukuna.",
    uploadMedia: "Sanya Hoto",
    messages: "Saƙonni",
    noMessages: "Babu saƙon da aka zaɓa",
    typeMessage: "Rubuta saƙo...",
    send: "Aika",
    cancel: "Soke",
    save: "Ajiye",
    delete: "Goge",
    partsSelected: "Kayan da aka zaɓa",
    compareDetails: "Kwatanta bayanai",
    clear: "Share",
    noPartsFound: "Babu kayayyakin da suka dace",
    reviews: "sake dubawa",
    footer: "© 2025 Kasuwar PartsHub. Duk haƙƙoƙi sun kiyaye.",
    wishlist: "Kayayyakin So",
    mechanics: "Makanikai",
    orders: "Dallaye",
    findMechanic: "Nemo Makaniki",
    myOrders: "Dallayen da na bayar",
    savedItems: "Abubuwan da aka Ajiye",
    compareParts: "Kwatanta Kayayyaki",
    conditionLabel: "Yanayi",
    gradeQuality: "Mataki / Inganci",
    ratingLabel: "Ƙima",
    descriptionLabel: "Bayanai",
    notSpecified: "Ba a bayyana ba",
    qrScanner: "Na'urar duba QR Code"
  },
  fr: {
    market: 'Marché',
    tracker: 'Suivi',
    sellers: 'Vendeurs',
    diyHub: 'Atelier DIY',
    inbox: 'Boîte de réception',
    garage: 'Garage',
    shop: 'Boutique',
    track: 'Suivre',
    diy: 'DIY',
    sellAPart: 'Vendre une pièce',
    signIn: 'Se connecter',
    nigeriaNumberOne: "Le n°1 au Nigeria",
    autoPartsMarketplace: "Marché de Pièces Automobiles",
    escrowProtected: "Protégé par Escrow",
    listingsCount: "Plus de 50k annonces",
    liveTracking: "Suivi en direct",
    searchPlaceholder: "Rechercher des pièces (ex. Plaquettes , Alternateur)...",
    filters: "Filtres",
    allParts: "Toutes les pièces",
    engine: "Moteur",
    transmission: "Transmission",
    brakes: "Freins",
    suspension: "Suspension",
    exterior: "Extérieur",
    interior: "Intérieur",
    viewDetails: "Voir les détails",
    addToCart: "Ajouter au panier",
    buyNow: "Acheter maintenant",
    conditionNew: "Neuf",
    conditionUsed: "Occasion",
    compare: "Comparer",
    checkout: "Payer",
    payNow: "Payer maintenant",
    orderSuccess: "Commande réussie !",
    viewReceipt: "Voir le reçu",
    myGarage: "Mon Garage",
    manageVehicles: "Gérez vos véhicules et trouvez exactement ce qui convient.",
    addVehicle: "Ajouter un véhicule",
    primary: "Principal",
    primaryVehicle: "Véhicule principal",
    noVehicles: "Aucun véhicule dans votre garage pour le moment.",
    uploadMedia: "Importer un média",
    messages: "Messages",
    noMessages: "Aucun message sélectionné",
    typeMessage: "Écrivez un message...",
    send: "Envoyer",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer",
    partsSelected: "Pièces sélectionnées",
    compareDetails: "Comparer les détails",
    clear: "Effacer",
    noPartsFound: "Aucune pièce ne correspond à vos critères",
    reviews: "avis",
    footer: "© 2025 PartsHub Marketplace. Tous droits réservés.",
    wishlist: "Liste de souhaits",
    mechanics: "Mécaniciens",
    orders: "Commandes",
    findMechanic: "Trouver un mécanicien",
    myOrders: "Mes commandes",
    savedItems: "Articles sauvegardés",
    compareParts: "Comparer les pièces",
    conditionLabel: "État",
    gradeQuality: "Niveau / Qualité",
    ratingLabel: "Évaluation",
    descriptionLabel: "Description",
    notSpecified: "Non spécifié",
    qrScanner: "Scanner de code QR"
  },
  zh: {
    market: '市场',
    tracker: '追踪器',
    sellers: '卖家',
    diyHub: 'DIY 中心',
    inbox: '收件箱',
    garage: '车库',
    shop: '商店',
    track: '追踪',
    diy: 'DIY',
    sellAPart: '出售零件',
    signIn: '登录',
    nigeriaNumberOne: "尼日利亚第一的",
    autoPartsMarketplace: "汽车配件市场",
    escrowProtected: "资金担保",
    listingsCount: "50,000+ 商品",
    liveTracking: "实时订单追踪",
    searchPlaceholder: "搜索零件（例如：刹车片、发电机）...",
    filters: "筛选",
    allParts: "所有零件",
    engine: "发动机",
    transmission: "变速箱",
    brakes: "刹车",
    suspension: "悬挂",
    exterior: "外观",
    interior: "内饰",
    viewDetails: "查看详情",
    addToCart: "加入购物车",
    buyNow: "立即购买",
    conditionNew: "全新",
    conditionUsed: "二手",
    compare: "对比",
    checkout: "结账",
    payNow: "立即付款",
    orderSuccess: "订单提交成功！",
    viewReceipt: "查看收据",
    myGarage: "我的车库",
    manageVehicles: "管理您的车辆，寻找完美适配的零件。",
    addVehicle: "添加车辆",
    primary: "主要",
    primaryVehicle: "主要车辆",
    noVehicles: "您的车库里暂时没有车辆。",
    uploadMedia: "上传文件",
    messages: "消息",
    noMessages: "未选择消息",
    typeMessage: "输入一条消息...",
    send: "发送",
    cancel: "取消",
    save: "保存",
    delete: "删除",
    partsSelected: "已选零件",
    compareDetails: "对比详情",
    clear: "清除",
    noPartsFound: "未找到符合您条件的零件",
    reviews: "条评价",
    footer: "© 2025 PartsHub 市场。保留所有权利。",
    wishlist: "心愿单",
    mechanics: "汽修工",
    orders: "订单",
    findMechanic: "寻找汽修工",
    myOrders: "我的订单",
    savedItems: "收藏的物品",
    compareParts: "较零件",
    conditionLabel: "状态",
    gradeQuality: "等级 / 质量",
    ratingLabel: "评分",
    descriptionLabel: "描述",
    notSpecified: "未说明",
    qrScanner: "二维码扫描器"
  }
};

type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => {
      if (prev === 'en') return 'ig';
      if (prev === 'ig') return 'yo';
      if (prev === 'yo') return 'ha';
      if (prev === 'ha') return 'fr';
      if (prev === 'fr') return 'zh';
      return 'en';
    });
  };

  const t = (key: keyof Translations) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
